# Generated by Django 3.2.5 on 2021-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
