# Generated by Django 3.2.5 on 2021-08-02 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210802_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prize',
            name='points',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(through='core.Membership', to='core.Organization'),
        ),
    ]
