# Generated by Django 3.2.5 on 2021-08-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210805_0242'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='required_grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grad_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
