# Generated by Django 3.2.5 on 2021-08-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='Regular Schedule', max_length=200),
            preserve_default=False,
        ),
    ]
