# Generated by Django 3.2.5 on 2021-08-07 00:58

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ical_links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('required', True), ('required_grad_year__isnull', True), ('type', 1)), models.Q(('required', False), ('required_grad_year__isnull', False), ('type', 2)), models.Q(('required', False), ('required_grad_year__isnull', True), ('type', 3)), _connector='OR'), name='core_organization_type'),
        ),
    ]
