# Generated by Django 3.2.5 on 2021-08-07 09:13

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210806_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ical_links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
