# Generated by Django 3.2.5 on 2021-08-07 09:43

from django.db import migrations, models


# Added manually
def set_categories(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    for org in Organization.objects.all():
        if org.type == 3:
            org.category = 1
            org.save()


# Added manually
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_organization_ical_links"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='core_organization_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.IntegerField(choices=[(1, 'Service'), (2, 'Competition'), (3, 'Interest')], null=True),
        ),
        migrations.RunPython(set_categories, reverse_func), # Added manually
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category__isnull', True), ('required', True), ('required_grad_year__isnull', True), ('type', 1)), models.Q(('category__isnull', True), ('required', False), ('required_grad_year__isnull', False), ('type', 2)), models.Q(('category__isnull', False), ('required', False), ('required_grad_year__isnull', True), ('type', 3)), _connector='OR'), name='core_organization_type'),
        ),
    ]
