# Generated by Django 3.2.5 on 2021-08-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210807_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Service'), (2, 'Competition'), (3, 'Interest')], null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
