# Generated by Django 3.2.5 on 2021-08-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_organizationlink'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='core_membership_user_organization'),
        ),
    ]
