# Generated by Django 3.2.5 on 2021-08-09 16:21

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_membership_core_membership_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.PositiveIntegerField(default=core.models.random_code, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, editable=False, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
