# Generated by Django 3.2.5 on 2021-08-10 19:05

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_membership_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
