# Generated by Django 3.2.5 on 2021-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('organization__type', 'organization__name')},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('type', 'name')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ('points',)},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-priority',)},
        ),
        migrations.AddField(
            model_name='event',
            name='submission_type',
            field=models.IntegerField(choices=[(1, 'Code'), (2, 'File')], default=1),
            preserve_default=False,
        ),
    ]
