# Generated by Django 3.2.5 on 2021-08-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Staff'), (3, 'Guest')], default=1),
            preserve_default=False,
        ),
    ]
