# Generated by Django 3.2.5 on 2021-08-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grad_year',
            field=models.IntegerField(blank=True, choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
    ]
