# Generated by Django 3.2.5 on 2021-08-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_user_grad_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleperiod',
            options={'ordering': ('start',)},
        ),
    ]
