# Generated by Django 3.2.5 on 2021-08-23 16:01

import core.models
from django.db import migrations, models
import random


# Added manually
def delete_extra_codes(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    Event.objects.exclude(submission_type=1).update(code=None)


# Added manually
def delete_extra_codes_reverse(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    for x in Event.objects.filter(code=None):
        x.code = random.randint(100000, 999999)
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_scheduleperiod_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="code",
            field=models.PositiveIntegerField(blank=True, default=core.models.random_code, null=True),
        ),
        migrations.RunPython(delete_extra_codes, delete_extra_codes_reverse),  # Added manually
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("code__isnull", False), ("submission_type", 1)),
                    models.Q(models.Q(("submission_type", 1), _negated=True), ("code__isnull", True)),
                    _connector="OR",
                ),
                name="core_event_submission_type_code",
            ),
        ),
    ]
