# Generated by Django 3.2.5 on 2021-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210823_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
