# Generated by Django 3.2.5 on 2021-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='submission_type',
            field=models.IntegerField(choices=[(1, 'Code'), (2, 'File')], default=1),
        ),
    ]
