# Generated by Django 3.2.5 on 2021-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_event_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
