# Generated by Django 3.2.5 on 2021-10-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_submission_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.PositiveIntegerField(blank=True, help_text='Only set if the number of points needs to be overriden for this user. If blank, defaults to the number of points the event is worth.', null=True),
        ),
    ]
