# Generated by Django 3.2.5 on 2022-01-23 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_submission_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
