# Generated by Django 3.2.5 on 2022-02-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_pollsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
