# Generated by Django 3.2.5 on 2022-04-10 21:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_membership_points_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('word', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('guesses', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]), blank=True, default=list, size=None)),
                ('solved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordleentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='core_wordleentry_user_date'),
        ),
    ]
