# Generated by Django 3.2.5 on 2022-04-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20220410_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordleentry',
            options={'verbose_name_plural': 'Wordle entries'},
        ),
    ]
