# Generated by Django 3.2.5 on 2022-04-10 22:34

import core.models
import core.wordle
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_wordleentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordleentry',
            name='guesses',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=5, validators=[core.models.validate_guess]), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='wordleentry',
            name='word',
            field=models.CharField(default=core.wordle.random_answer, max_length=5),
        ),
    ]
