# Generated by Django 3.2.5 on 2022-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220410_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wordle_streak',
            field=models.IntegerField(default=0),
        ),
    ]
